spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 10378
    timeout: 3000
    pool:
      max-idle: 50
      min-idle: 30
      max-active: 100
      max-wait: 2000
  rocketmq:
    cluster: zxCluster
    namesrvAddr: 127.0.0.1:9876
    instanceName: zxInstance
    topic: zxTopic
    fcTag: zxTag

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhangxi.bean
